
service: sls-lambda-docker

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  ecr:
    images:
      baseimage:
        path: ./
  apiGateway:
    binaryMediaTypes:
      - 'application/pdf'
    shouldStartNameWithService: true

functions:
  hello:
    image: baseimage
    events:
      - httpApi:
          path: /
          method: get